steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "us-central1-docker.pkg.dev/$PROJECT_ID/tradehills-bot-repo/tradehills-telegram-bot:$SHORT_SHA"
    - "."

- name: "gcr.io/cloud-builders/docker"
  args:
    - "push"
    - "us-central1-docker.pkg.dev/$PROJECT_ID/tradehills-bot-repo/tradehills-telegram-bot:$SHORT_SHA"

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud run deploy tradehills-telegram-bot \
        --image us-central1-docker.pkg.dev/$PROJECT_ID/tradehills-bot-repo/tradehills-telegram-bot:$SHORT_SHA \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --min-instances 1 \
        --clear-vpc-connector \
        --set-env-vars TOKEN=${_TOKEN},GROUP_ID=${_GROUP_ID}

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/tradehills-bot-repo/tradehills-telegram-bot:$SHORT_SHA"

options:
  # Send logs to a regional user-owned bucket instead of requiring a global bucket
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"
