steps:
  # 1) Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tradehills-telegram-bot:$SHORT_SHA',
        '.'
      ]

  # 2) Push it to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/tradehills-telegram-bot:$SHORT_SHA'
      ]

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      [
        '-c',
        |
          gcloud run deploy tradehills-telegram-bot \
            --image gcr.io/$PROJECT_ID/tradehills-telegram-bot:$SHORT_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars TOKEN=${_TOKEN},GROUP_ID=${_GROUP_ID}
      ]

# Make the newly built image available
images:
  - 'gcr.io/$PROJECT_ID/tradehills-telegram-bot:$SHORT_SHA'
